### ISSUE TITLE
what=ERROR: Unable to send iBEC component: Unable to upload data to device on iPod touch 5 

### ISSUE THREAD

**Issue by Goodgamer78** [LukeZGD/iOS-OTA-Downgrader#167]
Hello, I was attempting to restore my device in PWNdfu mode to iOS 8.4.1 using the script. When it extracts the IPSW and then try to Futurerestore, I get the following error. I am on a Mac. Anyone know a fix? 

Sending iBEC (282844 bytes)...
Cleaning up...
[exception]:
what=ERROR: Unable to send iBEC component: Unable to upload data to device

code=39845905
line=608
file=futurerestore.cpp
commit count=259:
commit sha  =a58821b95f6417ad649ed7a5460337dcd82e200e:
Done: restoring failed!

[Log] Restoring done! 
[Log] Downgrade script done!

**Comment by LukeZGD** [comment]
send full log please

**Comment by Anatoliy26041966** [comment]
*** Legacy iOS Kit ***
 - Script by LukeZGD -

* Version: v25.01.16 (852bb31)
* Platform: macos (15.2 - arm64) 

* Device: iPad 2 (Wi-Fi) (iPad2,1 - k93ap) in DFU mode
* iOS Version: Unknown
* To get iOS version, go to: Misc Utilities -> Get iOS Version
* ECID: 3177891245390

* Only select unmodified IPSW for the selection. Do not select custom IPSWs

* Selected Target (iOS 6.1.3) IPSW: ../iPad2,1_6.1.3_10B329_Restore.ipsw
* Selected Target IPSW is validated

* Selected Base (iOS 4.3.x) IPSW: /Users/anatoliy/Downloads/3uToolsDownloads/Firmware/iPad2,1_4.3.1_8G4_Restore.ipsw
* Base Version: 4.3.1-8G4
* Selected Base IPSW is validated

 > Main Menu > FourThree Utility > Step 1: Restore
[Input] Select an option:
   Select Target IPSW  
   Download Target IPSW  
   Select Base IPSW  
 -> Start Restore 
   Go Back  

[Input] Memory Option for creating custom IPSW
* When this option is enabled, system RAM will be used for the IPSW creation process.
* I recommend to enable this option to speed up creating the custom IPSW.
* However, if your PC/Mac has less than 8 GB of RAM, disable this option.
* This option is enabled by default (Y). Select this option if unsure.
[Input] Enable this option? (Y/n): 
 -> Yes 
   No  

[Log] Memory option enabled.

[Log] Found existing Custom IPSW. Skipping IPSW creation.
[Log] Checking firmware keys in ../resources/firmware/iPad2,1/8G4
[Log] Found existing saved 6.1.3 blobs: ../saved/shsh/3177891245390_iPad2,1_k93ap_6.1.3-10B329_3a88b7c3802f2f0510abc432104a15ebd8bd7154.shsh2
* Select Y if your device is in pwned iBSS/kDFU mode.
* Select N if this is not the case. (pwned using checkm8-a5)
* Failing to answer correctly will cause "Sending iBEC" to fail.
[Input] Is your device already in pwned iBSS/kDFU mode? (y/N): 
   No  
 -> Yes 

[Log] Pwned iBSS/kDFU mode specified by user.
[Log] Device iPad2,1 has no baseband/disabled baseband update
[Log] Extracting IPSW: ../iPad2,1_6.1.3_10B329_FourThree.ipsw
Archive:  ../iPad2,1_6.1.3_10B329_FourThree.ipsw
  inflating: ../iPad2,1_6.1.3_10B329_FourThree/048-2516-005.dmg  
  inflating: ../iPad2,1_6.1.3_10B329_FourThree/048-2634-005.dmg  
  inflating: ../iPad2,1_6.1.3_10B329_FourThree/048-2679-005.dmg  
  inflating: ../iPad2,1_6.1.3_10B329_FourThree/BuildManifest.plist  
   creating: ../iPad2,1_6.1.3_10B329_FourThree/Downgrade/
 extracting: ../iPad2,1_6.1.3_10B329_FourThree/Downgrade/RestoreDeviceTree  
  inflating: ../iPad2,1_6.1.3_10B329_FourThree/Downgrade/RestoreKernelCache  
  inflating: ../iPad2,1_6.1.3_10B329_FourThree/Downgrade/RestoreLogo  
   creating: ../iPad2,1_6.1.3_10B329_FourThree/Firmware/
   creating: ../iPad2,1_6.1.3_10B329_FourThree/Firmware/all_flash/
   creating: ../iPad2,1_6.1.3_10B329_FourThree/Firmware/all_flash/all_flash.k93ap.production/
  inflating: ../iPad2,1_6.1.3_10B329_FourThree/Firmware/all_flash/all_flash.k93ap.production/DeviceTree.k93ap.img3  
  inflating: ../iPad2,1_6.1.3_10B329_FourThree/Firmware/all_flash/all_flash.k93ap.production/LLB.k93ap.RELEASE.img3  
  inflating: ../iPad2,1_6.1.3_10B329_FourThree/Firmware/all_flash/all_flash.k93ap.production/applelogo.s5l8940x.img3  
  inflating: ../iPad2,1_6.1.3_10B329_FourThree/Firmware/all_flash/all_flash.k93ap.production/batterycharging0.s5l8940x.img3  
  inflating: ../iPad2,1_6.1.3_10B329_FourThree/Firmware/all_flash/all_flash.k93ap.production/batterycharging1.s5l8940x.img3  
  inflating: ../iPad2,1_6.1.3_10B329_FourThree/Firmware/all_flash/all_flash.k93ap.production/batteryfull.s5l8940x.img3  
  inflating: ../iPad2,1_6.1.3_10B329_FourThree/Firmware/all_flash/all_flash.k93ap.production/batterylow0.s5l8940x.img3  
  inflating: ../iPad2,1_6.1.3_10B329_FourThree/Firmware/all_flash/all_flash.k93ap.production/batterylow1.s5l8940x.img3  
  inflating: ../iPad2,1_6.1.3_10B329_FourThree/Firmware/all_flash/all_flash.k93ap.production/glyphcharging.s5l8940x.img3  
  inflating: ../iPad2,1_6.1.3_10B329_FourThree/Firmware/all_flash/all_flash.k93ap.production/glyphplugin.s5l8940x.img3  
  inflating: ../iPad2,1_6.1.3_10B329_FourThree/Firmware/all_flash/all_flash.k93ap.production/iBoot.k93ap.RELEASE.img3  
 extracting: ../iPad2,1_6.1.3_10B329_FourThree/Firmware/all_flash/all_flash.k93ap.production/manifest  
  inflating: ../iPad2,1_6.1.3_10B329_FourThree/Firmware/all_flash/all_flash.k93ap.production/recoverymode~ipad.s5l8940x.img3  
   creating: ../iPad2,1_6.1.3_10B329_FourThree/Firmware/dfu/
  inflating: ../iPad2,1_6.1.3_10B329_FourThree/Firmware/dfu/iBEC.k93ap.RELEASE.dfu  
  inflating: ../iPad2,1_6.1.3_10B329_FourThree/Firmware/dfu/iBSS.k93ap.RELEASE.dfu  
   creating: ../iPad2,1_6.1.3_10B329_FourThree/Firmware/usr/
   creating: ../iPad2,1_6.1.3_10B329_FourThree/Firmware/usr/local/
   creating: ../iPad2,1_6.1.3_10B329_FourThree/Firmware/usr/local/standalone/
  inflating: ../iPad2,1_6.1.3_10B329_FourThree/Restore.plist  
  inflating: ../iPad2,1_6.1.3_10B329_FourThree/kernelcache.release.k93  
 extracting: ../iPad2,1_6.1.3_10B329_FourThree/Firmware/all_flash/all_flash.k93ap.production/DeviceTreeB.img3  
 extracting: ../iPad2,1_6.1.3_10B329_FourThree/Firmware/all_flash/all_flash.k93ap.production/applelogoB.img3  
 extracting: ../iPad2,1_6.1.3_10B329_FourThree/Firmware/all_flash/all_flash.k93ap.production/iBootB.img3  
 extracting: ../iPad2,1_6.1.3_10B329_FourThree/Firmware/all_flash/all_flash.k93ap.production/recoverymodeB.img3  
[Log] Running idevicerestore with command: ../bin/macos/arm64/idevicerestore -ew "../iPad2,1_6.1.3_10B329_FourThree.ipsw"
Found device in DFU mode
Found ECID 3177891245390
Identified device as k93ap, iPad2,1
Extracting BuildManifest from IPSW
Product Version: 6.1.3
Product Build: 10B329 Major: 10
Device supports Image4: false
Variant: Customer Erase Install (IPSW)
This restore will erase your device data.
Getting ApNonce in dfu mode... 
checking for local shsh
Using cached SHSH
Using cached filesystem from '../iPad2,1_6.1.3_10B329_FourThree/048-2634-005.dmg'
Extracting iBSS.k93ap.RELEASE.dfu...
Personalizing IMG3 component iBSS...
reconstructed size: 76110
Sending iBSS (76110 bytes)...
[==================================================] 100.0%
Nonce: 
checking for local shsh
Using cached SHSH
Extracting iBEC.k93ap.RELEASE.dfu...
Personalizing IMG3 component iBEC...
reconstructed size: 289102
Sending iBEC (289102 bytes)...
[================================                  ]  62.3%ERROR: Unable to send iBEC component: Unable to upload data to device
ERROR: Unable to send iBEC to device
ERROR: Unable to place device into recovery mode from DFU mode

[Log] Restoring done! Read the message below if any error has occurred:
* If the restore failed on updating baseband:
 -> Try disabling baseband update: ./restore.sh --disable-bbupdate

* Please read the "Troubleshooting" wiki page in GitHub before opening any issue!
* Your problem may have already been addressed within the wiki page.
* If opening an issue in GitHub, please provide a FULL log/output. Otherwise, your issue may be dismissed.

* Save the terminal output now if needed. (macOS: Cmd+S, Linux: Ctrl+Shift+S)
* Legacy iOS Kit v25.01.16 (852bb31)
* Platform: macos (15.2 - arm64) 

anatoliy@MacBook-Air-Anatoliy ~ %
