### ISSUE TITLE
Cannot enter pwnDFU mode on iPad Air

### ISSUE THREAD

**Issue by Awii2** [LukeZGD/iOS-OTA-Downgrader#214]
When trying to enter pwnDFU mode using gaster, it gets stuck on 
`[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227`
When using ipwnDFU it gives `ValueError: The device has no langid` or no errors at all, the terminal just closes.

**Comment by Awii2** [comment]
Also sorry for asking a dumb question, but where do you find the logs?

**Comment by LukeZGD** [comment]
You can get the log by saving the terminal output (shortcut is Ctrl+Shift+S)

ipwndfu is mentioned though so that lets me know that this is running on a Linux system. Unfortunately, checkm8 for A7 devices is very unreliable on Linux, there is nothing I can do about it

You may read the Troubleshooting wiki page for more info
