### ISSUE TITLE
(iPad 2,3 CDMA) Downgrade script successful to 6.1.2 but reboots to iOS 9 after restart

### ISSUE THREAD

**Issue by Paskalampi** [LukeZGD/iOS-OTA-Downgrader#215]
[log.txt](https://github.com/LukeZGD/iOS-OTA-Downgrader/files/9642353/log.txt)

Ubuntu 22.04, using a live USB, log is attached. it completes fine but the ipad reboots back to normal like I didn't do anything to it

**Comment by LukeZGD** [comment]
This should now be fixed in 2022-09-26-122a6f4

Here is a warning though, since baseband update is disabled for iPad2,3:

    WARNING - Baseband update will be disabled for the custom IPSW.
    * With baseband update disabled, activation errors may occur.
    * Do NOT continue if you do not have other means for activation.

I would not recommend to continue without an Arduino+USB Host Shield on hand.

You may also add OpenSSH to the custom IPSW with jailbreak option enabled, this could also be useful (see `ipsw.sh` in `resources`). You will find these in lines 231 to 233:

    # adding sshdeb works for 6.1.3 only from what i've tested, doesn't seem to work on etasonjb ipsws
    #JBFiles+=("../resources/jailbreak/sshdeb.tar")                                       # uncomment to add openssh to custom ipsw
    #JailbreakFiles $JBURL/sshdeb.tar sshdeb.tar 0bffece0f8fd939c479159b57e923dd8c06191d3 # uncomment to add openssh to custom ipsw

Remove the first line, and remove the `#` at the beginning of JBFiles and JailbreakFiles:

    JBFiles+=("../resources/jailbreak/sshdeb.tar")                                       # uncomment to add openssh to custom ipsw
    JailbreakFiles $JBURL/sshdeb.tar sshdeb.tar 0bffece0f8fd939c479159b57e923dd8c06191d3 # uncomment to add openssh to custom ipsw

**Comment by Paskalampi** [comment]
i just ran the updated script as it is and it restored without an issue. activation wasn't a problem at all, thank you for fixing it so quickly. you helped me restore my childhood ipad that I've had since 2011 and now I can finally go back in time after several failed attempts. once again I really appreciate it
