### ISSUE TITLE
iPhone 4 3,1 not properly downgrading

### ISSUE THREAD

**Issue by AIMBOT312** [LukeZGD/iOS-OTA-Downgrader#218]
When trying to downgrade a 3,1 iPhone it completes the restore properly, then it reboots and shows an iOS 7 apple logo. It gets stuck on this logo indefinitely.

**Comment by LukeZGD** [comment]
Do you have a full log of the IPSW creation and restore process

**Comment by AIMBOT312** [comment]
Where can I find a log?

**Comment by LukeZGD** [comment]
You can get the log by saving the full terminal output (for Linux terminal emulators, shortcut is Ctrl+Shift+S)

**Comment by AIMBOT312** [comment]
https://paste.etechsystems.org/ayijoqoveb

Here is the log file.

**Comment by LukeZGD** [comment]
I can't seem to replicate this issue, probably some difference between Linux and Mac. Since you have access to macOS anyway, I would suggest to use [cherryflowerJB](https://web.archive.org/web/20210322151509/https://dora2ios.web.app/CFJB/) or [powdersn0w](https://dora2ios.web.app/konayuki/index.html) instead of iPhone4Down

**Comment by LukeZGD** [comment]
Found the actual issue: nvram values. Just follow the troubleshooting steps here: https://github.com/LukeZGD/iOS-OTA-Downgrader/wiki/Troubleshooting#clearing-nvram
