### ISSUE TITLE
iPhone 4'1 couldn't restore to iOS 6.1.3

### ISSUE THREAD

**Issue by germank96** [LukeZGD/iOS-OTA-Downgrader#272]
I'm sorry if this issue already have been added, but like 2-3 versions ago it used to work and after an update it stopped downgrading to iOS 6.1.3, but I could successfully downgrade to iOS 8.4.1.
[github.pdf](https://github.com/LukeZGD/iOS-OTA-Downgrader/files/10838634/github.pdf)

**Comment by LukeZGD** [comment]
Looks like a weird idevicererestore issue on Mac that I can't really fix, sorry. Maybe trying another restore will get past the issue you're experiencing. Also try deleting the saved folder before trying again.

Though since you're on a Mac, you also have the option to restore with the jailbreak option disabled, and then jailbreak after restoring with a patched p0sixspwn from https://archives.legacyjailbreak.com/
