### ISSUE TITLE
iPhone 5c iOS 8.4.1 support

### ISSUE THREAD

**Issue by Grandboy46** [LukeZGD/iOS-OTA-Downgrader#90]
Hey guys,

I noticed that ipsw files of iPhone 5 also compatible with iPhone 5c. iPhone 5 can be downgraded to iOS 8.4.1 with this tool. I think it would also be possible to save iPhone 5c ota blobs as iPhone 5 and use those to downgrade it. Can you please also add iPhone 5c support for iOS 8.4.1 oat downgrade. I have one:(

**Comment by LukeZGD** [comment]
Unfortunately it is impossible for iPhone 5C to be supported for OTA downgrade/restoring to 8.4.1.

iOS 8.4.1 OTA is only signed for devices that received iOS 6, the iPhone 5C never received iOS 6 because it shipped with iOS 7, so 8.4.1 OTA is not signed for them. (unless Apple suddenly signs them one day, which would be a miracle)

For iOS 10, the iPhone 5 and 5C use the same IPSW, but only because they combined the firmware components of the 4 devices into just 1 IPSW. When checking the iOS 10 IPSWs of iPhone_4.0_32bit, the files have support for these 4: n41 and n42, (iPhone 5), and n48 and n49 (for the 5C).

**Comment by Grandboy46** [comment]
really a shame:(
